/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Packages_Hung;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author hunglv
 */

public class Frame_Thong_Ke_Theo_Thang extends javax.swing.JFrame{

    /**
     * Creates new form Frame_Thong_Ke_Theo_Thang
     */
    Frame_Thong_Ke_Thoi_Gian thong_Ke_Thoi_Gian;
    Frame_Thong_Ke_Theo_Ngay hien_Thi_Theo_Ngay;
    DefaultTableModel model;
    int frame_static = 0;
    String time_year;
    public Frame_Thong_Ke_Theo_Thang(Frame_Thong_Ke_Thoi_Gian thong_Ke_Thoi_Gian, String time_year, 
                                    int frame_static) {
        initComponents();
        this.thong_Ke_Thoi_Gian = thong_Ke_Thoi_Gian;
        model = (DefaultTableModel) jTable1.getModel();
        this.time_year = time_year;
        this.frame_static = frame_static;
        push_data_in_table();
    }    

    private Frame_Thong_Ke_Theo_Thang() {
        throw new UnsupportedOperationException("Not supported yet."); 
    }
    
    private void push_data_in_table() {
        String txt = time_year;
        if (txt == " ") txt = "2019";
        ArrayList<Integer> list_thang = new ArrayList<>();
        for(int i=1; i<=12; i++) {
            list_thang.add(i);
        }
        DAO_Hoa_Don_Ban_Hang dhdbh = new DAO_Hoa_Don_Ban_Hang();
        int num_row = model.getRowCount();
        int tong_doanh_thu = 0;
        for (Integer thang : list_thang) {
            String date_month = thang + "/" + txt;
            int tong_tien = dhdbh.get_tong_tien_from_month(date_month);
            if (tong_tien > 0) {
                model.addRow(new Object[] {
                    (num_row+1), (thang + "/" + txt), tong_tien, "Detail " + (num_row+1)
                });
                num_row += 1;
                tong_doanh_thu += tong_tien;
            }
        }
        jLabel3.setText("" + tong_doanh_thu);
        jLabel1.setText("Xem Doanh Thu Theo Tháng Năm " + txt);
        //SET CUSTOM RENDERRER TO TEAMS COLUMN
        jTable1.getColumnModel().getColumn(3).setCellRenderer(new ButtonRenderer());
        
        jTable1.getColumnModel().getColumn(3).setCellEditor(new ButtonEditor(new JTextField()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Xem Doanh Thu Theo Tháng");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tháng", "Tổng Tiền", "Xem Chi Tiết"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Quay Lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Tổng Doanh Thu : ");

        jLabel3.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel2)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(183, 183, 183))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Come back Frame_Thong_Ke_Theo_Thoi_Gian
        if (frame_static == 0) {
            thong_Ke_Thoi_Gian.setVisible(true);
        }else {
            new Frame_Thong_Ke_Theo_Nam(thong_Ke_Thoi_Gian).setVisible(true);
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Thong_Ke_Theo_Thang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Thong_Ke_Theo_Thang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Thong_Ke_Theo_Thang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Thong_Ke_Theo_Thang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Thong_Ke_Theo_Thang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    class ButtonRenderer extends JButton implements  TableCellRenderer {
        //CONSTRUCTOR
        public ButtonRenderer() {
            //SET BUTTON PROPERTIES
            setOpaque(true);
        }
        @Override
        public Component getTableCellRendererComponent(JTable table, Object obj,
                boolean selected, boolean focused, int row, int col) {
            //SET PASSED OBJECT AS BUTTON TEXT
                setText((obj==null) ? "":obj.toString());
            return this;
        }
    }
    //BUTTON EDITOR CLASS
    class ButtonEditor extends DefaultCellEditor {
        protected JButton btn;
        private String lbl;
        private Boolean clicked;
        public ButtonEditor(JTextField txt) {
            super(txt);
            btn=new JButton();
            btn.setOpaque(true);
            btn.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    fireEditingStopped();
                }
            });
        }
        @Override
        public Component getTableCellEditorComponent(JTable table, Object obj,
            boolean selected, int row, int col) {
            //SET TEXT TO BUTTON,SET CLICKED TO TRUE,THEN RETURN THE BTN OBJECT
                lbl=(obj==null) ? "":obj.toString();
                btn.setText(lbl);
                clicked=true;
                return btn;
        }
        @Override
        public Object getCellEditorValue() {
            if (clicked == true) {
                String[] s = lbl.split(" ");
                int row = Integer.parseInt(s[1])-1;
                int column = 1;
                
                String date_month = String.valueOf(jTable1.getValueAt(row, column));
                System.out.println(date_month);
                setVisible(false);
                hien_Thi_Theo_Ngay = new Frame_Thong_Ke_Theo_Ngay(thong_Ke_Thoi_Gian, date_month, frame_static);
                hien_Thi_Theo_Ngay.setVisible(true);
            }
            clicked = false;
            return new String(lbl);
        }

        @Override
        public boolean stopCellEditing() {
            
            return super.stopCellEditing();
        }
        
    }
}
